name: "service-layer-v3-test"
description:  service layer test catalog
version: 0.1
category: Applications
maintainer: Kumar Chockalingam
license: # The license
projectURL: # A URL related to the catalog entry
